# Generated by Django 4.2 on 2024-12-08 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=255)),
                ('mac_address', models.CharField(max_length=17, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('mac_address', models.CharField(max_length=17)),
                ('hostname', models.CharField(max_length=255)),
                ('os_name', models.CharField(max_length=255)),
                ('os_version', models.CharField(max_length=255)),
                ('available_disk', models.TextField()),
                ('free_disk_space', models.CharField(max_length=255)),
                ('total_disk_space', models.CharField(max_length=255)),
            ],
        ),
    ]
