# Generated by Django 4.2 on 2024-12-31 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scanresult',
            name='hostname',
        ),
        migrations.RemoveField(
            model_name='scanresult',
            name='mac_address',
        ),
        migrations.AddField(
            model_name='scanresult',
            name='device',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='scan_results', to='devices.device'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='device',
            name='hostname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='scanresult',
            name='available_disk',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='scanresult',
            name='free_disk_space',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='scanresult',
            name='os_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='scanresult',
            name='os_version',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='scanresult',
            name='total_disk_space',
            field=models.CharField(max_length=100),
        ),
    ]
